Use quemepongo;
-- delete from map_conjunto_tipoprenda;
-- delete from map_prenda_atuendo;
-- delete from membrecia;
delete from foto;
delete from fotografo;
delete from estilos;
delete from superponible;
delete from materiales;
delete from tipoprenda;
delete from prenda;
delete from map_usuario_guardaropa;
delete from guardaropa;
delete from calificacionatuendo;
delete from conjuntospredefinidos;
delete from atuendo;
delete from usuario;
